add api endpoint for adding comments
kzzztkt/games_project pull request #6
Opened 2023-05-11 14:45 UTC by kzzztkt

ticket #7 
Endpoint for adding comments

2023-05-11 15:07 UTC, yalicee reviewed
You are missing the following tests:

Status 201, ignores unnecessary properties
Status 400, invalid ID, e.g. string of "not-an-id"
Status 404, non existent ID, e.g. 0 or 9999
Status 400, missing required field(s), e.g. no username or body properties
Status 404, username does not exist

2023-05-11 15:07 UTC, yalicee commented on __tests__/endpoints.test.js
> +                expect('votes' in body.comment).toBe(true);
you can test this with actual data since you know most of it

2023-05-12 09:07 UTC, merged

2023-05-12 09:09 UTC, B7Bprog requested changes
Hey Benjamin, Please see my comments, refactor your code, then run the tests. Once everything passes, feel free to merge it.

2023-05-12 09:09 UTC, B7Bprog commented on __tests__/endpoints.test.js
> +                expect(typeof body.comment.comment_id).toBe('number');
You could check the actual comment ID here.

2023-05-12 09:09 UTC, B7Bprog commented on __tests__/endpoints.test.js
> +    test('should respond: 201 with new comment ', () => {
You said: 'should respond: 201 with new comment', but you're only checking the status code.

2023-05-12 09:09 UTC, B7Bprog commented on __tests__/endpoints.test.js
> +        .expect(404)
Please also expect an error message here, not just a code.

2023-05-12 09:09 UTC, B7Bprog commented on __tests__/endpoints.test.js
> +        .expect(400)
Missing error message.

2023-05-12 09:09 UTC, B7Bprog commented on __tests__/endpoints.test.js
> +        .expect(404)
Missing error message.

2023-05-12 09:09 UTC, B7Bprog commented on controllers/postComments.controller.js
> +    // console.log(review_id);
Please remove all commented out code.

2023-05-12 09:09 UTC, B7Bprog commented on testDb.txt
> +You are now connected to database "nc_games_test" as user "benjohnson".
This file shouldn't be part of your PR.